---
- ec2_vpc_subnet_facts:
    filters:
      vpc-id: "{{ public_vpc_id }}"
    region: "{{ ec2_region }}"
  register: vpc_public_subnet

- set_fact:
    public_subnet_id: "{{ vpc_public_subnet.subnets[0].id }}"

- ec2_vpc_subnet_facts:
    filters:
      vpc-id: "{{ private_vpc_id }}"
    region: "{{ ec2_region }}"
  register: vpc_private_subnet

- set_fact:
    private_subnet_id_sidea: "{{ vpc_private_subnet.subnets[0].id }}"

- set_fact:
    private_subnet_id_sideb: "{{ vpc_private_subnet.subnets[1].id }}"